### PR TITLE
Added reporting

### PR DESCRIPTION
**Pull request by kelockhart**

### CODE REVIEW

**Comment by romanchyla** [comment]
I'm bit confused: the two PR's contain the same pieces of code - is it two different features? And if this report should be called often, then I'm afraid, I'll have to insist on making the change into the query to solr (plus adding a cache to avoid querying for the same orcidid multiple times). You could (should?) use the code that is inside the app.py

@kelockhart please provide more context

also, more docstrings for the functions please!

**Comment by kelockhart** [comment]
Argh yeah I noticed the commits from the other PR had snuck their way into this one - I thought I'd rebased from master but must have missed a step. I'll fix it.

I think the code will be run ~once per week, but I can add the cache and otherwise try to speed things up. Which code from app.py are you referring to? Adding the cache?

**Comment by romanchyla** [comment]
something along those lines: https://github.com/adsabs/ADSOrcid/blob/master/ADSOrcid/app.py#L569

**Comment by kelockhart** [comment]
@romanchyla I've made all of your requested changes - can you take a look again?

**Comment by romanchyla** [comment]
thanks!

**Pull request merged**
